-- MySQL Script generated by MySQL Workbench
-- Mon Jun 26 14:16:29 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_login
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_login
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_login` DEFAULT CHARACTER SET utf8 ;
USE `db_login` ;

-- -----------------------------------------------------
-- Table `db_login`.`FUNCAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_login`.`FUNCAO` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `cargo` VARCHAR(45) NOT NULL,
  `descricao` TINYTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO funcao(id,cargo,descricao) VALUE(1,"admin","Cargo obtido por administradores do espaco");
INSERT INTO funcao(id,cargo,descricao) VALUE(2,"user","Cargo que identifica todos os utilizadores do espaco");

-- -----------------------------------------------------
-- Table `db_login`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_login`.`USER` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `telemovel` VARCHAR(15) NOT NULL,
  `email` VARCHAR(75) NOT NULL,
  `registo_data` DATETIME NOT NULL,
  `ultimo_login` DATETIME NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `FUNCAO_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `FUNCAO_id`),
  INDEX `fk_USER_FUNCAO1_idx` (`FUNCAO_id` ASC) VISIBLE,
  CONSTRAINT `fk_USER_FUNCAO1`
    FOREIGN KEY (`FUNCAO_id`)
    REFERENCES `db_login`.`FUNCAO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;